import { _decorator } from 'cc';

// We create an enum for our text "keys". This prevents typos.
export enum ETextKey {
    PLAY,
    RESTART,
    JUMP,
    POWERUP_SPEED,
    POWERUP_MAGNET,
    POWERUP_CHILLIES,
    ENGLISH,
    HINDI,
    HIGH_SCORE,
    INFO_1_TITLE,
    INFO_1_DESC,
    INFO_2_TITLE,
    INFO_2_DESC,
    INFO_3_TITLE,
    INFO_3_DESC,
    HOW_TO_PLAY,
    // Add any new text keys here
}

// This is our translation database.
// 'en' = English, 'hi' = Hindi, 'en_HI' = Hinglish
export const localizationData = {
    'en': {
        [ETextKey.PLAY]: "PLAY",
        [ETextKey.RESTART]: "RESTART",
        [ETextKey.JUMP]: "JUMP",
        [ETextKey.POWERUP_SPEED]: "SPEED",
        [ETextKey.POWERUP_MAGNET]: "MAGNET",
        [ETextKey.POWERUP_CHILLIES]: "CHILLIES",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "हिन्दी",
        [ETextKey.HIGH_SCORE]: "HIGH SCORE !",
        [ETextKey.INFO_1_TITLE]: "LIVES TO\nGET CHILLIES",
        [ETextKey.INFO_1_DESC]: "AVOID THE OBSTACLES &\nCOLLECT CHILLIES",
        [ETextKey.INFO_2_TITLE]: "NEW PREMIUM\nFLAVOURS",
        [ETextKey.INFO_2_DESC]: "USE OUR NEW CHILLI\nBOOSTED FLAVOURS",
        [ETextKey.INFO_3_TITLE]: "MAX DISCOUNT\nAT SPINNEYS",
        [ETextKey.INFO_3_DESC]: "WIN EXCITING DISCOUNTS\n& SHARE SCORES",
        [ETextKey.HOW_TO_PLAY]: "HOW TO PLAY",
    },
    'hi': {
        [ETextKey.PLAY]: "खेलें",
        [ETextKey.RESTART]: "फिर से शुरू करें",
        [ETextKey.JUMP]: "जम्प",
        [ETextKey.POWERUP_SPEED]: "स्पीड",
        [ETextKey.POWERUP_MAGNET]: "मैगनेट",
        [ETextKey.POWERUP_CHILLIES]: "चिलीज़",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "हिन्दी",
        [ETextKey.HIGH_SCORE]: "उच्च स्कोर !",
        [ETextKey.INFO_1_TITLE]: "मिर्च खाने के\nलिए जीता है",
        [ETextKey.INFO_1_DESC]: "बाधाओं से बचें और\nमिर्च इकट्ठा करें",
        [ETextKey.INFO_2_TITLE]: "नए प्रीमियम\nफ्लेवर",
        [ETextKey.INFO_2_DESC]: "हमारे नए मिर्च-युक्त\nस्वादों का उपयोग करें",
        [ETextKey.INFO_3_TITLE]: "स्पिनीज़ पर\nधिकतम छूट",
        [ETextKey.INFO_3_DESC]: "रोमांचक छूट जीतें\nऔर स्कोर साझा करें",
        [ETextKey.HOW_TO_PLAY]: "कैसे खेलने के लिए",
    },
    'en_HI': {
        [ETextKey.PLAY]: "PLAY",
        [ETextKey.RESTART]: "RESTART",
        [ETextKey.JUMP]: "JUMP",
        [ETextKey.POWERUP_SPEED]: "RAFTAAR",
        [ETextKey.POWERUP_MAGNET]: "CHUMBAK",
        [ETextKey.POWERUP_CHILLIES]: "MIRCHIS",
        [ETextKey.ENGLISH]: "ENGLISH",
        [ETextKey.HINDI]: "HINGLISH",
        [ETextKey.HIGH_SCORE]: "Uchch Skor !",
        [ETextKey.INFO_1_TITLE]: "mirch khaane ke\nlie jeeta hai",
        [ETextKey.INFO_1_DESC]: "Baadhaon se bachen aur\nmirch ikattha karen",
        [ETextKey.INFO_2_TITLE]: "nae preemiyam\nphlevar",
        [ETextKey.INFO_2_DESC]: "Hamaare nae mirch-yukt\nsvaadon ka upayog karen",
        [ETextKey.INFO_3_TITLE]: "spineez par\nadhikatam chhoot",
        [ETextKey.INFO_3_DESC]: "Romaanchak chhoot jeeten\naur skor saajha karen",
        [ETextKey.HOW_TO_PLAY]: "kaise khelane ke lie",
    }
};
